name: Build and Release

on:
  push:
    branches:
      - main
      - ota

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu' 

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Install dependencies
      run: npm install

    - name: Build APK
      run: cd android && ./gradlew assembleRelease

    - name: Get current date and time
      id: date
      run: echo "RELEASE_TAG=v1.0.$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Upload APK to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: android/app/build/outputs/apk/release/app-release.apk
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        name: Release ${{ env.RELEASE_TAG }}
        body: "New release of the app"
        draft: true
        prerelease: false

    - name: CodePush release
      env:
        CODEPUSH_APP_NAME: ${{ secrets.CODEPUSH_APP_NAME }}
        CODEPUSH_DEPLOYMENT_NAME: ${{ secrets.CODEPUSH_DEPLOYMENT_NAME }}
        CODEPUSH_ACCESS_KEY: ${{ secrets.CODEPUSH_ACCESS_KEY }}
      run: |
        npm appcenter codepush release-react -a $CODEPUSH_APP_NAME -d $CODEPUSH_DEPLOYMENT_NAME --token $CODEPUSH_ACCESS_KEY
